### ISSUE TITLE
Unnecessary div

### ISSUE THREAD

**Issue by jim-rosales** [amydcrawford/prj-rev-bwfs-tea-cozy#4]
You don't really need this div as its causing issues, on chrome this is how the page rendered for me. 

![screen shot 2018-10-17 at 7 32 09 pm](https://user-images.githubusercontent.com/28379087/47127772-5970b300-d243-11e8-88d9-fe1addffadca.png)

It's causing margins to be added on all sides. 

If you want to apply CSS to the body you can do so by targeting the `body` element directly like so:
```CSS
/* Sans .*/
body {
  font-family: Helvetica;
  font-size: 22px;
  color: seashell;
  background-color: black;
  z-index: 1;
  opacity: 0.9;
  justify-content: center;
  width: 100%;
  margin: 0;
  padding: 0;
  text-align: center;
}
```

Then you can go ahead and deleted the `body div` and the page should render as expected:

![screen shot 2018-10-17 at 7 34 11 pm](https://user-images.githubusercontent.com/28379087/47127842-a18fd580-d243-11e8-8d3e-51dab8238e30.png)

https://github.com/amydcrawford/prj-rev-bwfs-tea-cozy/blob/4efd8945737ce0b1b0303b0bd21a04ee0f98735e/TeaCozy/index.html#L7
